reg_stats = [
     " 1. Total Career Games Played:",  
     " 2. Total Career Minutes Played:",
     " 3. Field Goals Made :",
     " 4. Field Goals Attempted:",
     " 5. 2-Pointers Made:",
     " 6. 2-Pointers Attempted:", 
     " 7. 3-Pointers Made:",
     " 8. 3-Pointers Attempted:",
     " 9. Free Throws Made:",
     "10. Free Throws Attempted:",
     "11. Offensive Rebounds:",
     "12. Defensive Rebounds:",
     "13. Total Rebounds:",
     "14. Assists:",
     "15. Steals:",
     "16. Blocks:",
     "17. Points:",
     "18. Field Goal Percentage:",
     "19. 2-Point Percentage:",
     "20. 3-Point Percentage:"
]

adv_stats = [
     "21. Effective Field Goal Percentage:",
     "22. Free Throw Percentage:",
     "23. Trueshooting Percentage:",
     "24. 3-Point Attempt Rate:",
     "25. Free Throw Attempt Rate:",
     "26. Offensive Rebound Percentage:",
     "27. Defensive Rebound Percentage:",
     "28. Assist Percentage:",
     "29. Steal Percentage:",
     "30. Block Percentage:",
     "31. Offensive Rating:",
     "32. Defensive Rating:",
     "33. Offensive Win Shares:",
     "34. Defensive Win Shares:",
     "35. Win Shares Per 48 Minutes:",
     "36. Offensive Box Plus/Minus:",
     "37. Defensive Box Plus/Minus:",
     "38. Box Plus/Minus:",
     "39. Value Over Replacement Player (VORP):"
]

adv_desc = [
     "    - This statistic adjusts for the fact that a 3-point field goal is worth one more point than a 2-point field goal.",
     "",
     "    - A measure of shooting efficiency that takes into account 2-point field goals, 3-point field goals, and free throws.",
     "    - Percentage of FG Attempts from 3-Point Range",
     "    - Number of FT Attempts Per FG Attempt",
     "    - An estimate of the percentage of available offensive rebounds a player grabbed while on the floor.",
     "    - An estimate of the percentage of available defensive rebounds a player grabbed while on the floor.",
     "    - An estimate of the percentage of teammate field goals a player assisted while on the floor.",
     "    - An estimate of the percentage of opponent possessions that end with a steal while on the floor.",
     "    - An estimate of the percentage of opponent two-point field goal attempts blocked by while on the floor.",  
     "    - An estimate of points produced (players, or scored teams, per 100 possessions)",
     "    - An estimate of points allowed per 100 possessions",
     "    - An estimate of the number of wins contributed by a player due to his offense.", 
     "    - An estimate of the number of wins contributed by a player due to his defense.",
     "    - An estimate of the number of wins contributed by a player per 48 minutes (league average is approximately .100)",
     "    - A box score estimate of the offensive points per 100 possessions a player contributed above a league-average player.",
     "    - A box score estimate of the defensive points per 100 possessions a player contributed above a league-average player.", 
     "    - A box score estimate of the points per 100 possessions a player contributed above a league-average player.",
     "    - An estimate of the points per 100 possessions that a player contributed above a replacement-level."
]