reg_stats = [
     " 1. Total Career Games Played:",  
     " 2. Total Career Minutes Played:",
     " 3. Field Goals Made :",
     " 4. Field Goals Attempted:",
     " 5. 2-Pointers Made:",
     " 6. 2-Pointers Attempted:", 
     " 7. 3-Pointers Made:",
     " 8. 3-Pointers Attempted:",
     " 9. Free Throws Made:",
     "10. Free Throws Attempted:",
     "11. Offensive Rebounds:",
     "12. Defensive Rebounds:",
     "13. Total Rebounds:",
     "14. Assists:",
     "15. Steals:",
     "16. Blocks:",
     "17. Points:",
     "18. Field Goal Percentage:",
     "19. 2-Point Percentage:",
     "20. 3-Point Percentage:"
]

adv_stats = [
     "21. Effective Field Goal Percentage:",
     "22. Free Throw Percentage:",
     "23. Trueshooting Percentage:",
     "24. 3-Point Attempt Rate:",
     "25. Free Throw Attempt Rate:",
     "26. Offensive Rebound Percentage:",
     "27. Defensive Rebound Percentage:",
     "28. Assist Percentage:",
     "29. Steal Percentage:",
     "30. Block Percentage:",
     "31. Offensive Rating:",
     "32. Defensive Rating:",
     "33. Offensive Win Shares:",
     "34. Defensive Win Shares:",
     "35. Win Shares Per 48 Minutes:",
     "36. Offensive Box Plus/Minus:",
     "37. Defensive Box Plus/Minus:",
     "38. Box Plus/Minus:",
     "39. Value Over Replacement Player (VORP):"
]

adv_desc = [
     "This statistic adjusts for the fact that a 3-point field goal is worth one more point than a 2-point field goal.",
     "",
     "A measure of shooting efficiency that takes into account 2-point field goals, 3-point field goals, and free throws.",
     "Percentage of FG Attempts from 3-Point Range",
     "Number of FT Attempts Per FG Attempt",
     "An estimate of the percentage of available offensive rebounds a player grabbed while on the floor.",
     "An estimate of the percentage of available defensive rebounds a player grabbed while on the floor.",
     "An estimate of the percentage of teammate field goals a player assisted while on the floor.",
     "An estimate of the percentage of opponent possessions that end with a steal while on the floor.",
     "An estimate of the percentage of opponent two-point field goal attempts blocked by while on the floor.",  
     "An estimate of points produced (players, or scored teams, per 100 possessions)",
     "An estimate of points allowed per 100 possessions",
     "An estimate of the number of wins contributed by a player due to his offense.", 
     "An estimate of the number of wins contributed by a player due to his defense.",
     "An estimate of the number of wins contributed by a player per 48 minutes (league average is approximately .100)",
     "A box score estimate of the offensive points per 100 possessions a player contributed above a league-average player.",
     "A box score estimate of the defensive points per 100 possessions a player contributed above a league-average player.", 
     "A box score estimate of the points per 100 possessions a player contributed above a league-average player.",
     "An estimate of the points per 100 possessions that a player contributed above a replacement-level."
]

# this is where the user will choose which stats they want to evaluate 
# user will also be prompted to input a number from 1 to 10 as weight for the importance of each stat
cat_dict = {
     1 : "games_played", 
     2 : "mp",
     3 : "fg" ,
     4 : "fga", 
     5 : "two_p", 
     6 : "two_pa",
     7 : "three_p", 
     8 : "three_pa",
     9 : "ft", 
    10 : "fta",
    11 : "orb", 
    12 : "drb", 
    13 : "trb", 
    14 : "ast", 
    15 : "stl",
    16 : "blk", 
    17 : "pts", 
    18 : "fg_pct", 
    19 : "two_p_pct", 
    20 : "three_p_pct", 
    21 : "efg_pct", 
    22 : "ft_pct", 
    23 : "trueshooting_pct", 
    24 : "three_par",
    25 : "ftr", 
    26 : "orb_pct", 
    27 : "drb_pct",  
    28 : "ast_pct", 
    29 : "stl_pct", 
    30 : "blk_pct", 
    31 : "ortg", 
    32 : "drtg", 
    33 : "ows", 
    34 : "dws", 
    35 : "ws", 
    36 : "obpm", 
    37 : "dbpm",  
    38 : "bpm", 
    39 : "vorp" 
}

cat_name = {
     "games_played" : "GP", 
     "mp" : "MP",
     "fg" : "FGM",
     "fga" : "FGA", 
     "two_p" : "2PM", 
     "two_pa" : "2PA",
     "three_p" : "3PM", 
     "three_pa" : "3PA",
     "ft" : "FTs", 
     "fta" : "FTA",
     "orb" : "OffRebs", 
     "drb" : "DefRebs", 
     "trb" : "TotalReb", 
     "ast" : "AST", 
     "stl" : "STLS",
     "blk" : "BLKS", 
     "pts" : "PTS", 
     "fg_pct" : "FG%", 
     "two_p_pct" : "2P%", 
     "three_p_pct" : "3P%", 
     "efg_pct" : "EFG%", 
     "ft_pct" : "FT%", 
     "trueshooting_pct" : "TS%", 
     "three_par" : "3PARate",
     "ftr" : "FTARate", 
     "orb_pct" : "OffReb%", 
     "drb_pct" : "DefReb%",  
     "ast_pct" : "AST%", 
     "stl_pct" : "STL%", 
     "blk_pct" : "BLK%", 
     "ortg" : "Off RTG", 
     "drtg" : "Def RTG", 
     "ows" : "Off WS", 
     "dws" : "Def WS", 
     "ws" : "WS per 48 Min", 
     "obpm" : "Off Box Plus/Minus" , 
     "dbpm" : "Def Box Plus/Minus",  
     "bpm" : "Box Plus/Minus", 
     "vorp" : "VORP"
}