user_prompt = [
      "Welcome!\n",
     "This your very own NBA Greatest of All Time (G.O.A.T, Calculator!)",
     "Here you will be able to customize and create your customized statistical G.O.A.T",
     "\nInstructions:",
     "1, Input a number from 1 to 39 in order to choose statistical category.",
     "2, Input a weight from 1 to 10 indicating indicating importance for G.O.A.T calculation",
     "3, When finished enter 40 to calculate!", 
     "\nUNLESS SPECIFIED, ASSUME ALL CATEGORIES ARE PER GAME\n",
     "REGULAR STATS:",
     " 1. Total Career Games Played",  
     " 2. Total Career Minutes Played",
     " 3. Field Goals Made ",
     " 4. Field Goals Attempted",
     " 5. 2-Pointers Made",
     " 6. 2-Pointers Attempted", 
     " 7. 3-Pointers Made",
     " 8. 3-Pointers Attempted",
     " 9. Free Throws Made",
     "10. Free Throws Attempted",
     "11. Offensive Rebounds",
     "12. Defensive Rebounds",
     "13. Total Rebounds",
     "14. Assists",
     "15. Steals",
     "16. Blocks",
     "17. Points",
     "18. Field Goal Percentage",
     "19. 2-Point Percentage",
     "20. 3-Point Percentage",
     "\nADVANCED STATS:",
     "21. "  + "Effective Field Goal Percentage"    ,
     "    - This statistic adjusts for the fact that a 3-point field goal is worth one more point than a 2-point field goal.",
     "22. "  + "Free Throw Percentage"    ,
     "23. "  + "Trueshooting Percentage"    ,
     "    - A measure of shooting efficiency that takes into account 2-point field goals, 3-point field goals, and free throws.",
     "24. "  + " 3-Point Attempt Rate"    ,
     "    - Percentage of FG Attempts from 3-Point Range",
     "25. "  +  "Free Throw Attempt Rate"    ,
     "    - Number of FT Attempts Per FG Attempt",
     "26. "  +  "Offensive Rebound Percentage"    ,
     "    - An estimate of the percentage of available offensive rebounds a player grabbed while on the floor.",
     "27. "  +  "Defensive Rebound Percentage"    ,
     "    - An estimate of the percentage of available defensive rebounds a player grabbed while on the floor.",
     "28. "  +  "Assist Percentage"    ,
     "    - An estimate of the percentage of teammate field goals a player assisted while on the floor.",
     "29. "  +  "Steal Percentage"    ,
     "    - An estimate of the percentage of opponent possessions that end with a steal while on the floor.",
     "30. "  + "Block Percentage"    ,
     "    - An estimate of the percentage of opponent two-point field goal attempts blocked by while on the floor.",  
     "31. "  + "Offensive Rating"    ,
     "    - An estimate of points produced (players, or scored (teams, per 100 possessions",
     "32. "  + "Defensive Rating"    ,
     "    - An estimate of points allowed per 100 possessions",
     "33. "  + "Offensive Win Shares"    ,
     "    - An estimate of the number of wins contributed by a player due to his offense.", 
     "34. "  + "Defensive Win Shares"    ,
     "    - An estimate of the number of wins contributed by a player due to his defense.",
     "35. "  + "Win Shares Per 48 Minutes"    ,
     "    - An estimate of the number of wins contributed by a player per 48 minutes (league average is approximately .100)",
     "36. "  + "Offensive Box Plus/Minus"    ,
     "    - A box score estimate of the offensive points per 100 possessions a player contributed above a league-average player.",
     "37. "  + "Defensive Box Plus/Minus"    ,
     "    - A box score estimate of the defensive points per 100 possessions a player contributed above a league-average player.", 
     "38. "  + "Box Plus/Minus"    ,
     "    - A box score estimate of the points per 100 possessions a player contributed above a league-average player.",
     "39. "  + "Value Over Replacement Player (VORP)"    ,
     "    - An estimate of the points per 100 possessions that a player contributed above a replacement-level (-2.0, player",
     "40. "  + "CALCULATE!"    
]